(in-package #:cl-user)

(defpackage #:place-utils
  (:nicknames #:place)
  (:use #:cl)
  (:shadow #:define-modify-macro)
  ;; Novel
  (:export #:&place
	   #:define-modify-macro
	   #:setf-expanderlet
	   #:with-resolved-places
	   
	   #:updatef
	   #:bulkf
	   ;#:setfnew

	   ;#:proxyf
	   ;#:call-next-customizer
	   #:cachef
	   #:oldf
	   #:readf
	   #:tracef)
  ;; Traditional
  (:export ; A corresponding modify-macro has deliberately not been provided for the following functions:
           ;macro-function class-of remf asin asinh atan atanh caaaar caaadr caaar caadar caaddr caadr cadaar cadadr cadar caddar cadddr caddr cdaaar cdaadr cdaar cdadar cdaddr cdadr cddaar cddadr cddar cdddar cddddr cdddr cis compile-file-pathname compiler-macro-function conjugatef cosf coshf denominator eighth exp expt file-length file-namestring file-position file-stream file-string-length file-write-date fill-pointer find-symbol integer-length isqrt log mod ninth sin sinh sixth sqrt tan tanh tenth
   ; #:char-codef #:char-intf #:char-namef #:code-charf
	   #:andf
	   #:appendf
	   #:applyf
	   #:ashf
	   #:bit-andf
	   #:bit-andc1f
	   #:bit-andc2f
	   #:bit-eqvf
	   #:bit-iorf
	   #:bit-nandf
	   #:bit-norf
	   #:bit-notf
	   #:bit-orc1f
	   #:bit-orc2f
	   #:bit-xorf
	   #:boolef
	   #:booleanf
	   #:butlastf
	   #:caarf
	   #:cadrf
	   #:carf
	   #:cdarf
	   #:cddrf
	   #:cdrf
	   #:ceilingf
	   #:char-downcasef
	   #:char-upcasef
	   #:characterf
	   #:coercef
	   #:compilef
	   #:complementf
	   #:concatenatef
	   #:constantlyf
	   #:copy-alistf
	   #:copy-listf
	   #:copy-pprint-dispatchf
	   #:copy-readtablef
	   #:copy-seqf
	   #:copy-structuref
	   #:copy-symbolf
	   #:copy-treef
	   #:deletef
	   #:delete-duplicatesf
	   #:delete-iff
	   #:delete-if-notf
	   #:deposit-fieldf
	   #:digit-charf
	   #:digit-char-pf
	   #:directoryf
	   #:directory-namestringf
	   #:dpbf
	   #:enough-namestringf
	   #:evalf
	   #:fceilingf
	   #:fdefinitionf
	   #:ffloorf
	   #:fifthf
	   #:find-classf
	   #:find-packagef
	   #:find-restartf
	   #:firstf
	   #:floatf
	   #:floorf
	   #:fourthf
	   #:froundf
	   #:ftruncatef
	   #:funcallf
	   #:gcdf
	   #:host-namestringf
	   #:internf
	   #:intersectionf
	   #:lastf
	   #:lcmf
	   #:ldbf
	   #:ldifff
	   #:lengthf
	   #:listf
	   #:list*f
	   #:list-lengthf
	   #:logandf
	   #:logandc1f
	   #:logandc2f
	   #:logcountf
	   #:logeqv
	   #:logical-pathnamef
	   #:logiorf
	   #:lognandf
	   #:lognorf
	   #:lognotf
	   #:logorc1f
	   #:logorc2f
	   #:logxorf
	   #:macroexpandf
	   #:macroexpand-1f
	   #:make-load-formf
	   #:make-load-form-saving-slotsf
	   #:make-random-statef
	   #:mapf
	   #:mapcanf
	   #:mapcarf
	   #:mapconf
	   #:maplistf
	   #:mask-fieldf
	   #:maxf
	   #:mergef
	   #:merge-pathnames
	   #:minf
	   #:name-char
	   #:namestringf
	   #:nbutlastf
	   #:nconcf
	   #:nintersectionf
	   #:notf
	   #:nreconcf
	   #:nreversef
	   #:nset-differencef
	   #:nset-exclusive-orf
	   #:nstring-capitalizef
	   #:nstring-downcasef
	   #:nstring-upcasef
	   #:nsublisf
	   #:nsubstf
	   #:nsubst-iff
	   #:nsubst-if-notf
	   #:nsubstitutef
	   #:nsubstitute-iff
	   #:nsubstitute-if-notf
	   #:nthf
	   #:nthcdrf
	   #:nunionf
	   #:orf
	   #:pairlisf
	   #:parse-integerf
	   #:parse-namestringf
	   #:pathnamef
	   #:prin1-to-stringf
	   #:princ-to-stringf
	   #:probe-filef
	   #:rationalf
	   #:rationalizef
	   #:removef
	   #:remove-duplicatesf
	   #:remove-iff
	   #:remove-if-notf
	   #:replacef
	   #:restf
	   #:revappendf
	   #:reversef
	   #:roundf
	   #:scale-floatf
	   #:secondf
	   #:set-differencef
	   #:set-exclusive-orf
	   #:sortf
	   #:stable-sortf
	   #:stringf
	   #:string-capitalizef
	   #:string-downcasef
	   #:string-left-trimf
	   #:string-right-trimf
	   #:string-trimf
	   #:string-upcasef
	   #:sublisf
	   #:subseqf
	   #:substf
	   #:subst-iff
	   #:subst-if-notf
	   #:substitutef
	   #:substitute-iff
	   #:substitute-if-notf
	   #:thirdf
	   #:translate-logical-pathnamef
	   #:translate-pathnamef
	   #:truenamef
	   #:truncatef
	   #:unionf
	   #:vectorf
	   #:vector-popf
	   #:vector-pushf
	   #:vector-push-extendf
	   #:write-to-stringf))
